In [1]:
import pandas as pd

In [6]:
ba=pd.read_csv(r"C:\Users\LENOVO\Downloads\jsbach_chorals_harmony\jsbach_chorals_harmony.data",header=None)
ba

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,000106b_,1,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,3,F_M
1,000106b_,2,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,E,5,C_M
2,000106b_,3,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,E,2,C_M
3,000106b_,4,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,3,F_M
4,000106b_,5,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,2,F_M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5660,015505b_,105,NO,NO,YES,NO,NO,NO,NO,YES,NO,NO,YES,NO,G,4,G_m
5661,015505b_,106,NO,NO,YES,NO,NO,NO,NO,YES,NO,YES,NO,NO,G,3,G_m
5662,015505b_,107,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,C,5,C_M
5663,015505b_,108,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,YES,NO,C,3,C_M
5664,015505b_,109,NO,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,4,F_M

In [10]:
name=[["Choral ID","Event number","Pitch classes","Pitch classes","Pitch classes","Pitch classes","Pitch classes",
       "Pitch classes","Pitch classes","Pitch classes","Pitch classes","Pitch classes","Pitch classes","Pitch classes",
       "Bass","Meter","Chord label"]]

In [11]:
ba.columns=name

In [12]:
ba

,Choral ID,Event number,Pitch classes,Pitch classes,Pitch classes,Pitch classes,Pitch classes,Pitch classes,Pitch classes,Pitch classes,Pitch classes,Pitch classes,Pitch classes,Pitch classes,Bass,Meter,Chord label
0,000106b_,1,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,3,F_M
1,000106b_,2,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,E,5,C_M
2,000106b_,3,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,E,2,C_M
3,000106b_,4,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,3,F_M
4,000106b_,5,YES,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,2,F_M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5660,015505b_,105,NO,NO,YES,NO,NO,NO,NO,YES,NO,NO,YES,NO,G,4,G_m
5661,015505b_,106,NO,NO,YES,NO,NO,NO,NO,YES,NO,YES,NO,NO,G,3,G_m
5662,015505b_,107,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,NO,NO,C,5,C_M
5663,015505b_,108,YES,NO,NO,NO,YES,NO,NO,YES,NO,NO,YES,NO,C,3,C_M
5664,015505b_,109,NO,NO,NO,NO,NO,YES,NO,NO,NO,YES,NO,NO,F,4,F_M

In [13]:
ba.to_csv("bach.csv")