In [1]:
import pandas as pd

In [3]:
l=pd.read_csv(r"C:\Users\LENOVO\Desktop\Behavior of the urban traffic of the city of Sao Paulo in Brazil.csv",sep=';',header=None)
l

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,Hour (Coded),Immobilized bus,Broken Truck,Vehicle excess,Accident victim,Running over,Fire vehicles,Occurrence involving freight,Incident involving dangerous freight,Lack of electricity,Fire,Point of flooding,Manifestations,Defect in the network of trolleybuses,Tree on the road,Semaphore off,Intermittent Semaphore,Slowness in traffic (%)
1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"4,1"
2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"6,6"
3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"8,7"
4,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"9,2"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,23,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,"17,8"
132,24,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,"18,1"
133,25,1,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,"17,7"
134,26,0,4,0,0,0,0,0,0,0,0,0,1,0,0,1,0,"17,4"
135,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"12,1"

In [5]:
l1=pd.read_csv(r"C:\Users\LENOVO\Desktop\iBeacon_RSSI_Unlabeled.csv",header=None)
l1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,location,date,b3001,b3002,b3003,b3004,b3005,b3006,b3007,b3008,b3009,b3010,b3011,b3012,b3013
1,?,11-7-2016 12:29:01,-200,-200,-80,-200,-77,-56,-81,-200,-200,-200,-200,-200,-200
2,?,11-7-2016 12:29:00,-200,-200,-80,-200,-78,-56,-200,-200,-200,-200,-200,-200,-200
3,?,11-7-2016 12:28:59,-200,-200,-81,-200,-74,-63,-200,-200,-200,-200,-200,-200,-200
4,?,11-7-2016 12:28:58,-200,-200,-200,-200,-75,-56,-200,-200,-200,-200,-200,-200,-200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5187,?,7-28-2016 14:14:50,-81,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200
5188,?,7-28-2016 14:14:49,-81,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200
5189,?,7-28-2016 14:14:48,-81,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200
5190,?,7-28-2016 14:14:47,-81,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200
5191,?,7-28-2016 14:14:46,-81,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200,-200

In [6]:
l.to_csv("Brazil labelled.csv")

In [7]:
l1.to_csv("Brazil unlabelled.csv")